stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint.py --verbose=0 include/framing/framing.h

Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/framing_test
  
Test Types:
  stage: test
  tags:
    - bfs
  script:
    - ./build/framing_test
